# Generated by Django 5.0.2 on 2024-04-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_date_category_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
