# Generated by Django 5.0.2 on 2024-04-29 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.TextField(default='blank-img.png')),
            ],
        ),
    ]
